// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureAccount = `-- name: EnsureAccount :exec
UPDATE agents
SET balance_cc = $2, updated_at = now()
WHERE id = $1 AND balance_cc = 0
`

type EnsureAccountParams struct {
	ID        string
	BalanceCc int64
}

func (q *Queries) EnsureAccount(ctx context.Context, arg EnsureAccountParams) error {
	_, err := q.db.Exec(ctx, ensureAccount, arg.ID, arg.BalanceCc)
	return err
}

const getAccountBalanceByAgentID = `-- name: GetAccountBalanceByAgentID :one
SELECT balance_cc
FROM agents
WHERE id = $1
`

func (q *Queries) GetAccountBalanceByAgentID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceByAgentID, id)
	var balance_cc int64
	err := row.Scan(&balance_cc)
	return balance_cc, err
}

const getAccountBalanceByAgentIDForUpdate = `-- name: GetAccountBalanceByAgentIDForUpdate :one
SELECT balance_cc
FROM agents
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountBalanceByAgentIDForUpdate(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceByAgentIDForUpdate, id)
	var balance_cc int64
	err := row.Scan(&balance_cc)
	return balance_cc, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id AS agent_id, balance_cc, updated_at
FROM agents
WHERE ($1::text = '' OR id = $1)
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountsParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListAccountsRow struct {
	AgentID   string
	BalanceCc int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(&i.AgentID, &i.BalanceCc, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE agents
SET balance_cc = $1, updated_at = now()
WHERE id = $2
`

type UpdateAccountBalanceParams struct {
	BalanceCc int64
	ID        string
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.BalanceCc, arg.ID)
	return err
}
