// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blacklistAgent = `-- name: BlacklistAgent :exec
INSERT INTO agent_blacklist (agent_id, reason)
VALUES ($1, $2)
ON CONFLICT (agent_id) DO UPDATE
SET reason = EXCLUDED.reason, created_at = now()
`

type BlacklistAgentParams struct {
	AgentID string
	Reason  string
}

func (q *Queries) BlacklistAgent(ctx context.Context, arg BlacklistAgentParams) error {
	_, err := q.db.Exec(ctx, blacklistAgent, arg.AgentID, arg.Reason)
	return err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, api_key_hash, status, claim_code)
VALUES ($1, $2, $3, 'pending', $4)
`

type CreateAgentParams struct {
	ID         string
	Name       string
	ApiKeyHash string
	ClaimCode  string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.Exec(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.ApiKeyHash,
		arg.ClaimCode,
	)
	return err
}

const createAgentKey = `-- name: CreateAgentKey :exec
INSERT INTO agent_keys (id, agent_id, provider, api_key_hash, status)
VALUES ($1, $2, $3, $4, 'active')
`

type CreateAgentKeyParams struct {
	ID         string
	AgentID    string
	Provider   string
	ApiKeyHash string
}

func (q *Queries) CreateAgentKey(ctx context.Context, arg CreateAgentKeyParams) error {
	_, err := q.db.Exec(ctx, createAgentKey,
		arg.ID,
		arg.AgentID,
		arg.Provider,
		arg.ApiKeyHash,
	)
	return err
}

const getAgentBlacklistReasonByAgentID = `-- name: GetAgentBlacklistReasonByAgentID :one
SELECT reason
FROM agent_blacklist
WHERE agent_id = $1
`

func (q *Queries) GetAgentBlacklistReasonByAgentID(ctx context.Context, agentID string) (string, error) {
	row := q.db.QueryRow(ctx, getAgentBlacklistReasonByAgentID, agentID)
	var reason string
	err := row.Scan(&reason)
	return reason, err
}

const getAgentByAPIKeyHash = `-- name: GetAgentByAPIKeyHash :one
SELECT id, name, api_key_hash, status, COALESCE(claim_code, '') AS claim_code, created_at
FROM agents
WHERE api_key_hash = $1
`

type GetAgentByAPIKeyHashRow struct {
	ID         string
	Name       string
	ApiKeyHash string
	Status     string
	ClaimCode  string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetAgentByAPIKeyHash(ctx context.Context, apiKeyHash string) (GetAgentByAPIKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getAgentByAPIKeyHash, apiKeyHash)
	var i GetAgentByAPIKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Status,
		&i.ClaimCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, api_key_hash, status, COALESCE(claim_code, '') AS claim_code, created_at
FROM agents
WHERE id = $1
`

type GetAgentByIDRow struct {
	ID         string
	Name       string
	ApiKeyHash string
	Status     string
	ClaimCode  string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetAgentByID(ctx context.Context, id string) (GetAgentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i GetAgentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Status,
		&i.ClaimCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentClaimByAgentID = `-- name: GetAgentClaimByAgentID :one
SELECT id, id AS agent_id, COALESCE(claim_code, '') AS claim_code, status, created_at
FROM agents
WHERE id = $1
`

type GetAgentClaimByAgentIDRow struct {
	ID        string
	AgentID   string
	ClaimCode string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAgentClaimByAgentID(ctx context.Context, id string) (GetAgentClaimByAgentIDRow, error) {
	row := q.db.QueryRow(ctx, getAgentClaimByAgentID, id)
	var i GetAgentClaimByAgentIDRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ClaimCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentClaimByClaimCode = `-- name: GetAgentClaimByClaimCode :one
SELECT id, id AS agent_id, COALESCE(claim_code, '') AS claim_code, status, created_at
FROM agents
WHERE claim_code = $1
`

type GetAgentClaimByClaimCodeRow struct {
	ID        string
	AgentID   string
	ClaimCode string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAgentClaimByClaimCode(ctx context.Context, claimCode string) (GetAgentClaimByClaimCodeRow, error) {
	row := q.db.QueryRow(ctx, getAgentClaimByClaimCode, claimCode)
	var i GetAgentClaimByClaimCodeRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ClaimCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentKeyByAPIKeyHash = `-- name: GetAgentKeyByAPIKeyHash :one
SELECT id, agent_id, provider, api_key_hash, status, created_at
FROM agent_keys
WHERE api_key_hash = $1
`

func (q *Queries) GetAgentKeyByAPIKeyHash(ctx context.Context, apiKeyHash string) (AgentKey, error) {
	row := q.db.QueryRow(ctx, getAgentKeyByAPIKeyHash, apiKeyHash)
	var i AgentKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Provider,
		&i.ApiKeyHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLastSuccessfulKeyBindAtByAgentID = `-- name: GetLastSuccessfulKeyBindAtByAgentID :one
SELECT created_at
FROM agent_key_attempts
WHERE agent_id = $1 AND status = 'success'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulKeyBindAtByAgentID(ctx context.Context, agentID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulKeyBindAtByAgentID, agentID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const listAgentKeyAttemptStatusesByAgentID = `-- name: ListAgentKeyAttemptStatusesByAgentID :many
SELECT status
FROM agent_key_attempts
WHERE agent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAgentKeyAttemptStatusesByAgentID(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAgentKeyAttemptStatusesByAgentID, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, api_key_hash, status, COALESCE(claim_code, '') AS claim_code, created_at
FROM agents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentsParams struct {
	Limit  int32
	Offset int32
}

type ListAgentsRow struct {
	ID         string
	Name       string
	ApiKeyHash string
	Status     string
	ClaimCode  string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKeyHash,
			&i.Status,
			&i.ClaimCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentStatusClaimed = `-- name: MarkAgentStatusClaimed :exec
UPDATE agents
SET status = 'claimed'
WHERE id = $1
`

func (q *Queries) MarkAgentStatusClaimed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAgentStatusClaimed, id)
	return err
}

const recordAgentKeyAttempt = `-- name: RecordAgentKeyAttempt :exec
INSERT INTO agent_key_attempts (id, agent_id, provider, status)
VALUES ($1, $2, $3, $4)
`

type RecordAgentKeyAttemptParams struct {
	ID       string
	AgentID  string
	Provider string
	Status   string
}

func (q *Queries) RecordAgentKeyAttempt(ctx context.Context, arg RecordAgentKeyAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAgentKeyAttempt,
		arg.ID,
		arg.AgentID,
		arg.Provider,
		arg.Status,
	)
	return err
}
