// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (id, agent_id, type, amount_cc, ref_type, ref_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLedgerEntryParams struct {
	ID       string
	AgentID  string
	Type     string
	AmountCc int64
	RefType  string
	RefID    string
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.AgentID,
		arg.Type,
		arg.AmountCc,
		arg.RefType,
		arg.RefID,
	)
	return err
}

const listLeaderboard = `-- name: ListLeaderboard :many
SELECT a.id, a.name, COALESCE(SUM(l.amount_cc), 0)::bigint AS net_cc
FROM agents a
LEFT JOIN ledger_entries l ON l.agent_id = a.id
GROUP BY a.id, a.name
ORDER BY net_cc DESC
LIMIT $1 OFFSET $2
`

type ListLeaderboardParams struct {
	Limit  int32
	Offset int32
}

type ListLeaderboardRow struct {
	ID    string
	Name  string
	NetCc int64
}

func (q *Queries) ListLeaderboard(ctx context.Context, arg ListLeaderboardParams) ([]ListLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardRow{}
	for rows.Next() {
		var i ListLeaderboardRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NetCc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, agent_id, type, amount_cc, ref_type, ref_id, created_at
FROM ledger_entries
WHERE ($1::text = '' OR agent_id = $1)
  AND ($2::text = '' OR (ref_type = 'hand' AND ref_id = $2))
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListLedgerEntriesParams struct {
	Column1 string
	Column2 string
	Column3 pgtype.Timestamptz
	Column4 pgtype.Timestamptz
	Limit   int32
	Offset  int32
}

func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Type,
			&i.AmountCc,
			&i.RefType,
			&i.RefID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
