// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID         string
	HandID     string
	AgentID    string
	ActionType string
	AmountCc   int64
	CreatedAt  pgtype.Timestamptz
}

type Agent struct {
	ID         string
	Name       string
	ApiKeyHash string
	BalanceCc  int64
	Status     string
	ClaimCode  string
	UpdatedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type AgentActionRequest struct {
	ID         string
	SessionID  string
	RequestID  string
	TurnID     string
	ActionType string
	AmountCc   pgtype.Int8
	ThoughtLog pgtype.Text
	Accepted   bool
	Reason     pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type AgentBlacklist struct {
	AgentID   string
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type AgentEventOffset struct {
	SessionID   string
	LastEventID string
	UpdatedAt   pgtype.Timestamptz
}

type AgentKey struct {
	ID         string
	AgentID    string
	Provider   string
	ApiKeyHash string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type AgentKeyAttempt struct {
	ID        string
	AgentID   string
	Provider  string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type AgentSession struct {
	ID        string
	AgentID   string
	RoomID    string
	TableID   pgtype.Text
	SeatID    pgtype.Int4
	JoinMode  string
	Status    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	ClosedAt  pgtype.Timestamptz
}

type Hand struct {
	ID            string
	TableID       string
	WinnerAgentID pgtype.Text
	PotCc         pgtype.Int8
	StreetEnd     pgtype.Text
	StartedAt     pgtype.Timestamptz
	EndedAt       pgtype.Timestamptz
}

type LedgerEntry struct {
	ID        string
	AgentID   string
	Type      string
	AmountCc  int64
	RefType   string
	RefID     string
	CreatedAt pgtype.Timestamptz
}

type ProviderRate struct {
	Provider            string
	PricePer1kTokensUsd float64
	CcPerUsd            float64
	Weight              float64
	UpdatedAt           pgtype.Timestamptz
}

type ProxyCall struct {
	ID               string
	AgentID          string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      pgtype.Int4
	Model            pgtype.Text
	Provider         pgtype.Text
	CostCc           int64
	CreatedAt        pgtype.Timestamptz
}

type Room struct {
	ID           string
	Name         string
	MinBuyinCc   int64
	SmallBlindCc int64
	BigBlindCc   int64
	Status       string
	CreatedAt    pgtype.Timestamptz
}

type Table struct {
	ID           string
	RoomID       pgtype.Text
	Status       string
	SmallBlindCc int64
	BigBlindCc   int64
	CreatedAt    pgtype.Timestamptz
}

type TableReplayEvent struct {
	ID            string
	TableID       string
	HandID        pgtype.Text
	GlobalSeq     int64
	HandSeq       pgtype.Int4
	EventType     string
	ActorAgentID  pgtype.Text
	Payload       []byte
	SchemaVersion int32
	CreatedAt     pgtype.Timestamptz
}

type TableReplaySnapshot struct {
	ID            string
	TableID       string
	AtGlobalSeq   int64
	StateBlob     []byte
	SchemaVersion int32
	CreatedAt     pgtype.Timestamptz
}
