// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: provider_rates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureDefaultProviderRate = `-- name: EnsureDefaultProviderRate :exec
INSERT INTO provider_rates (provider, price_per_1k_tokens_usd, cc_per_usd, weight)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider) DO NOTHING
`

type EnsureDefaultProviderRateParams struct {
	Provider            string
	PricePer1kTokensUsd float64
	CcPerUsd            float64
	Weight              float64
}

func (q *Queries) EnsureDefaultProviderRate(ctx context.Context, arg EnsureDefaultProviderRateParams) error {
	_, err := q.db.Exec(ctx, ensureDefaultProviderRate,
		arg.Provider,
		arg.PricePer1kTokensUsd,
		arg.CcPerUsd,
		arg.Weight,
	)
	return err
}

const getProviderRateByProvider = `-- name: GetProviderRateByProvider :one
SELECT provider, price_per_1k_tokens_usd, cc_per_usd, weight, updated_at
FROM provider_rates
WHERE provider = $1
`

func (q *Queries) GetProviderRateByProvider(ctx context.Context, provider string) (ProviderRate, error) {
	row := q.db.QueryRow(ctx, getProviderRateByProvider, provider)
	var i ProviderRate
	err := row.Scan(
		&i.Provider,
		&i.PricePer1kTokensUsd,
		&i.CcPerUsd,
		&i.Weight,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderRates = `-- name: ListProviderRates :many
SELECT provider, price_per_1k_tokens_usd, cc_per_usd, weight, updated_at
FROM provider_rates
ORDER BY provider ASC
`

func (q *Queries) ListProviderRates(ctx context.Context) ([]ProviderRate, error) {
	rows, err := q.db.Query(ctx, listProviderRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderRate{}
	for rows.Next() {
		var i ProviderRate
		if err := rows.Scan(
			&i.Provider,
			&i.PricePer1kTokensUsd,
			&i.CcPerUsd,
			&i.Weight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProxyCall = `-- name: RecordProxyCall :exec
INSERT INTO proxy_calls (id, agent_id, prompt_tokens, completion_tokens, total_tokens, model, provider, cost_cc)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordProxyCallParams struct {
	ID               string
	AgentID          string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      pgtype.Int4
	Model            pgtype.Text
	Provider         pgtype.Text
	CostCc           int64
}

func (q *Queries) RecordProxyCall(ctx context.Context, arg RecordProxyCallParams) error {
	_, err := q.db.Exec(ctx, recordProxyCall,
		arg.ID,
		arg.AgentID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.Model,
		arg.Provider,
		arg.CostCc,
	)
	return err
}

const upsertProviderRate = `-- name: UpsertProviderRate :exec
INSERT INTO provider_rates (provider, price_per_1k_tokens_usd, cc_per_usd, weight)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider) DO UPDATE
SET price_per_1k_tokens_usd = EXCLUDED.price_per_1k_tokens_usd,
    cc_per_usd = EXCLUDED.cc_per_usd,
    weight = EXCLUDED.weight,
    updated_at = now()
`

type UpsertProviderRateParams struct {
	Provider            string
	PricePer1kTokensUsd float64
	CcPerUsd            float64
	Weight              float64
}

func (q *Queries) UpsertProviderRate(ctx context.Context, arg UpsertProviderRateParams) error {
	_, err := q.db.Exec(ctx, upsertProviderRate,
		arg.Provider,
		arg.PricePer1kTokensUsd,
		arg.CcPerUsd,
		arg.Weight,
	)
	return err
}
